import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {
  ClerkProvider,
} from '@clerk/nextjs'
import "./globals.css";

import { QueryProvider } from "@/providers/query-provider";
import SheetProvider from "@/providers/sheet-provider";

import { Toaster } from "@/components/ui/sonner"

const font = Inter({ subsets: ["latin"] });



export const metadata: Metadata = {
  title: "Finance",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={font.className}>
          <QueryProvider>
            <SheetProvider />
            <Toaster />
            {children}
          </QueryProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
